- README.md
- manifests/init.pp
- spec/classes/dhcp_spec.rb
Fixes puppetlabs/puppetlabs-dhcp#34
> Cleanup 34

- manifests/init.pp
- manifests/params.pp
- spec/classes/dhcp_spec.rb
- spec/defines/host_spec.rb
- spec/defines/pool_spec.rb
Move to use ::osfamily
- includes a few changes to manifests
- lots more tests
> Move to use osfamily

- manifests/init.pp
dhcpd.conf file should be of type Concat rather than File.
> Changed dhcpd.conf File dependency to Concat.

- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf-header.erb
> Add 'authoritative' parameter

- .msync.yml
- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- README.md
- metadata.json
- spec/spec_helper.rb
> Modulesync 0.12.1 & Release 1.0.0

- manifests/init.pp
- manifests/pool.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf-header.erb
- templates/dhcpd.pool.erb
> add mtu option

- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf.ddns.erb
Add ability to use 'ad-hoc', 'standard' and 'none' ddns-update-style, in addition to the hardcoded 'interim'
> Added ddns-update-style option

- README.md
> correct misleading documentation for pool ranges

- .gitignore
- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
> modulesync 0.12.7

- CHANGELOG.md
- metadata.json
> release: 1.0.1

- spec/classes/dhcp_spec.rb
As pointed out by daenney, the description for tests was poorly worded
> Clarify test names

- manifests/init.pp
- spec/classes/dhcp_spec.rb
Added dhcpd_conf_filename param. Makes to possible to change the conf filename to dhcpd6.conf
> added dhcpd_conf_filename param

- .gitignore
- .msync.yml
- .rubocop.yml
- Gemfile
- spec/acceptance/nodesets/docker/centos-5.yml
- spec/acceptance/nodesets/docker/centos-6.yml
- spec/acceptance/nodesets/docker/centos-7.yml
- spec/acceptance/nodesets/docker/debian-7.yml
- spec/acceptance/nodesets/docker/debian-8.yml
- spec/acceptance/nodesets/docker/ubuntu-12.04.yml
- spec/acceptance/nodesets/docker/ubuntu-14.04.yml
- spec/acceptance/nodesets/docker/ubuntu-16.04.yml
- spec/classes/dhcp_spec.rb
- spec/defines/host_spec.rb
- spec/defines/pool_spec.rb
- spec/spec_helper.rb
> modulesync 0.15.0

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .msync.yml
- .travis.yml
- README.md
- manifests/init.pp
- metadata.json
- spec/default_facts.yml
- templates/dhcpd.conf-header.erb
Having a parameter list in the README removes the need to dig into
the code in order to determine what parameters are available on
the parameterized class.
> add parameter list

- manifests/dhcp_class.pp
- spec/defines/dhcp_class_spec.rb
- templates/dhcpd.class.erb
> Add dhcp_class define to create custom DHCP class

- README.md
- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf-header.erb
Creates a new key section for configuring access to the OMAPI service.
Fixes #90
> Add omapi_name, key, algorithm parameters

- .github/CONTRIBUTING.md
- .msync.yml
- .overcommit.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- spec/classes/dhcp_spec.rb
> modulesync 0.21.0

- README.md
- manifests/init.pp
- spec/classes/dhcp_spec.rb
I've added in some basic args to allow an ENC to easily pass in items for creating the defined resources.
> Added resource args for use with an ENC

- manifests/params.pp
> FreeBSD uses ISC DHCP 4.3 now

- manifests/params.pp
- spec/classes/dhcp_spec.rb
> Support SmartOS

- manifests/init.pp
- templates/dhcpd.conf-extra.erb
> Update $extra_config to work with arrays and not only strings

- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.service
* Works for any system with systemd service provider
* Adds spec for new case also
New PR over https://github.com/voxpupuli/puppet-dhcp/pull/129/files
> Write a systemd service file when using systemd

- manifests/init.pp
- manifests/params.pp
- spec/classes/dhcp_spec.rb
- spec/defines/dhcp_class_spec.rb
- spec/defines/host_spec.rb
- spec/defines/ignoredsubnet_spec.rb
- spec/defines/pool6_spec.rb
- spec/defines/pool_spec.rb
> Replace legacy facts with  facts hash

- manifests/init.pp
- manifests/params.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.service
> use parameter for dhcpd binary path in unit file

- manifests/failover.pp
- templates/dhcpd.service
Use dhcpd_conf_filename param instead of hard coded "dhcpd.conf" string
> Use dhcpd_conf_filename param

- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf.ddns.erb
useful for ddns environment to stop clients sending ddns updates
> add ddns_client_updates parameter

- metadata.json
> allow puppetlabs/concat 5.x

- .sync.yml
- .travis.yml
- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance.rb
> enable acceptance tests

- metadata.json
> fix wrong version schema in metadata.json

- manifests/params.pp
> update FreeBSD pkg name

- manifests/init.pp
> set dhcpd_ifaces in rc.conf on FreeBSD

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .msync.yml
- .travis.yml
- Dockerfile
- Gemfile
- Rakefile
- examples/init.pp
- manifests/dhcp_class.pp
- manifests/host.pp
- manifests/ignoredsubnet.pp
- manifests/pool.pp
- manifests/pool6.pp
- metadata.json
> modulesync 2.5.1 & drop Puppet 4

- .msync.yml
- .travis.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 2.7.0

- .sync.yml
- .travis.yml
> drop Ubuntu 14.04 support

- .github/SECURITY.md
- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- examples/init.pp
- manifests/disable.pp
- manifests/failover.pp
- manifests/host.pp
- manifests/ignoredsubnet.pp
- manifests/init.pp
- manifests/params.pp
- spec/spec_helper_acceptance.rb
> modulesync 3.0.0 & puppet-lint updates

- types/syslogfacility.pp
puppet-lint flagged these lines
> Resolve puppet-lint notices

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- .pmtignore
- Gemfile
- manifests/host.pp
- spec/defines/dhcp_class_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
> modulesync 7.2.0

- metadata.json
> Add OracleLinux/Alma/Rocky support

- CHANGELOG.md
- metadata.json
> Release 6.1.0
