- manifests/pool.pp
- templates/dhcpd.pool.erb
This allows users to specify different nameservers and a PXE-server. It also minimizes the differences to theforeman/dhcp which already includes these parameters.
> Add nameservers and pxeserver parameters to pool

- .fixtures.yml
- .gitignore
- .travis.yml
- Gemfile
- README.md
- Rakefile
- manifests/failover.pp
- manifests/host.pp
- manifests/init.pp
- manifests/params.pp
- manifests/pool.pp
- spec/classes/dhcp_spec.rb
- spec/defines/host_spec.rb
- spec/defines/pool_spec.rb
- spec/spec_helper.rb
- templates/debian/default_isc-dhcp-server
- templates/dhcpd.conf-header.erb
- templates/dhcpd.conf.ddns.erb
- templates/redhat/sysconfig-dhcpd
- tests/init.pp
> Modernize Module

- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf-header.erb
This allows one to add arbitrary global options to the main dhcpd.conf file, the same way the module already deals with arbitrary options in a specific pool.
> Added globaloptions parameter to dhcp class

- templates/dhcpd.host.erb
If dhcpd.host.erb normalises all MAC addresses into upper case then this makes duplicate MAC address detection easier.
In our use case XenServer only notices MACs are duplicated if they are the same case so we want to ensure that everywhere MACs are used they are in upper case.
> Normalise MAC addresses to upper case in dhcpd.host

- manifests/host.pp
- spec/defines/host_spec.rb
- templates/dhcpd.host.erb
This is particularly useful for appliances and hardware with specific requirements when using DHCP.  A good example is in the unit tests, setting `option vendor-encapsulated-options 01:04:31:41:50:43;` is sometimes necessary for APC PDUs to accept a DHCP lease.
> Allow additional options to be specified for dhcp::host

- spec/defines/host_spec.rb
- templates/dhcpd.host.erb
This is a non-backwards compatible change, at least in terms of the change that would occur to a DHCP server's config files.  This change is partially to incorporate what's done by theforeman-dhcp into this module (theforeman/puppet-dhcp#21).
Per the man page for dhcpd.conf it seems like ddns-hostname is used first when determing a client's hostname.
The DHCP server determines the client’s hostname by first looking for a ddns-hostname configuration option, and using that if it is present.  If no such option is present, the server looks for a valid hostname in the FQDN option sent by
the client.  If one is found, it is used; otherwise, if the client sent a host-name option, that is used.  Otherwise, if there is a host declaration that applies to the client, the name from that declaration …
> Set ddns-hostname instead of option host-name for host declarations

- README.md
- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf.ddns.erb
This is an attempt to migrate some of the options currently available in theforeman-dhcp into the puppetlabs module.  This new parameter would at least ease the transition from theforeman-dhcp to puppetlabs-dhcp, which I believe is a goal of the Foreman developers.
> Add dnskeyname parameter

- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf.ntp.erb
If `ntpservers` is not defined the `validate_array` validation fails.  I wrote the unit tests and stashed my changes to manifests/init.pp and templates/dhcpd.conf.ntp.erb which resulted in this error:
```
Puppet::Error:
"" is not an Array.  It looks to be a String
```
> Fix default ntpservers value to not fail validation

- README.md
I couldn't get the dhcp:pool as is in documentation to work. Using an array instead of a string works.
> Fix in documentation for dhcp::pool. range should be array instead of string

- README.md
- manifests/init.pp
- spec/classes/dhcp_spec.rb
- spec/lib/module_spec_helper.rb
- spec/spec_helper.rb
- templates/dhcpd.conf-header.erb
Add ability to define `omapi-port`.  I also added some helper functions to unit tests to verify contents of concat::fragment resources.  Hopefully simplify further unit testing of the contents.
This is a partial of what was in #29.
> Add omapi_port parameter

- templates/dhcpd.pool.erb
If you declare a domain name in a `dhcp::pool` declaration, the dhcp subnet block that gets generated has the domain name as a bare word, with no quotes:
#################################
#################################
subnet 10.1.2.0 netmask 255.255.255.0 {
option domain-name example.com;
option subnet-mask 255.255.255.0;
option routers 10.1.2.1;
option domain-name-servers 10.1.2.3;
}
This is not legal syntax - the domain name must be quoted:
option domain-name "example.com";
> properly put ""quotes around the domain-name option in pool declarations

- manifests/pool.pp
- templates/dhcpd.pool.erb
Enabling ignore unknown-clients, this is a fairly useful feature especially if you are operating within more complex DHCP set-ups. It's enabled on a per pool level as configuring it on the global config level severely cripples reconfigurability.
> Enable Ignore unknown clients in templating

- templates/dhcpd.pool.erb
dns servers in dhcp are listed in priority order.  by sorting the
dns server list, you are destroying the priority order specified
by the person calling the defined type.
> do not sort pool dns servers list

- manifests/init.pp
- templates/dhcpd.conf-extra.erb
Currently this is the only way I can think of to add conditional logic to the configuration file.  For instance, I need this in dhcpd.conf for razor:
if exists user-class and option user-class = "iPXE" {
filename "bootstrap.ipxe";
} else {
filename "undionly.kpxe";
}
> Add the ability to add extra configurations in plain-text

- README.md
- manifests/init.pp
- spec/classes/dhcp_spec.rb
- templates/dhcpd.conf.pxe.erb
- tests/init.pp
This commit adds support for iPXE chain loading, which allows a user to
specify a ipxe file and bootstrap script. When configured pxe will load
ipxe, which will then load the bootstrap script. This is helpful for
applications that use ipxe to load, like razor. Without this change it
is not possible to chain pxe to ipxe.
> Add support for iPXE chain loading

- spec/classes/dhcp_spec.rb
This commit fixes a typo in dhcp spec tests. Specifically, Dawin is corrected to Darwin.
> Fix typo in spec test

- README.md
- spec/defines/host_spec.rb
- templates/dhcpd.host.erb
The "comment" parameter is already supported by the dhcp::host class,
but the value is not passed through to the dhcp.host.erb  template.
If $comment parameter is not empty, add a line with a leading "#" and the comment to the host reservation entry.
Also add "comment =>" to the example host entry in README.md
> Add optional "comment" field to host template.

- manifests/init.pp
The service subscribing to concat resources does somehow not retain
execution order. But having the resources notify the service does.
When freshly setting up dhcpd on Debian jessie with their current puppet 3.7.2-4 and puppetlabs-concat 2.0.1-2 package I get:
root@node1:~# rm -f /etc/dhcp/dhcpd.{hosts,pools,conf}
root@node1:~# systemctl stop isc-dhcp-server
root@node1:~# puppet agent -t 
Notice: /Stage[main]/Dhcp/Concat[/etc/dhcp/dhcpd.conf]/File[/etc/dhcp/dhcpd.conf]/ensure: defined content as '{md5}cd59a406bb9a5f11d2f2f775e713c6f2'
Notice: /Stage[main]/Dhcp/Concat[/etc/dhcp/dhcpd.pools]/File[/etc/dhcp/dhcpd.pools]/ensure: defined content as '{md5}6560f465d270d816d0afd202343f2bee'
Error: Could not start Service[isc-dhcp-server]: Execution of '/usr/sbin/service isc-dhcp-server start' …
> Work around notification problem with concat resources

- manifests/init.pp
- spec/classes/dhcp_spec.rb
per [dhcp.conf(5)](http://manpages.ubuntu.com/manpages/xenial/man5/dhcpd.conf.5.html), and from https://github.com/theforeman/puppet-dhcp/commit/411bb90462129ca572b07e43481564acc9020e1f.
> Use ISC default for default_lease_time

- manifests/host.pp
If a non-string gets through to the template, [bad things](https://github.com/voxpupuli/puppet-dhcp/issues/109) happen.  Nicer to catch it in the manifest.
> Add parameter validation to dhcp::host

- manifests/host.pp
- spec/defines/host_spec.rb
- templates/dhcpd.host.erb
This allows for a dhcp host to be ignored by the dhcp server.  Used for
when the host should be handled by another dhcp server in the same
subnet.
> Allow for dhcp host to be ignored

- metadata.json
And we test with latest and that works.
This'll make it work for folks using Librarian and other modules that do concat 2.
> metadata: Concat 2 is backwards compatible with 1

- manifests/ignoredsubnet.pp
Add define documentation in manifests/ignoresubnet.pp so that it passes puppet-lint without a warning.
> Document the define in manifests/ignoredsubnet.pp

- spec/defines/pool6_spec.rb
- templates/dhcpd.pool.erb
- templates/dhcpd.pool6.erb
According to dhcpd.conf man page:
> Dynamic BOOTP leases are not compatible with failover, and, as such,
> you need to disallow BOOTP in pools that you are using failover for.
[https://linux.die.net/man/5/dhcpd.conf](https://linux.die.net/man/5/dhcpd.conf) (Chapter: Configuring Failover)
> deny dynamic bootp clients if failover is set

- metadata.json
We currently only run automated tests against Puppet 3 latest and
therefore cannot guarantee that this module works as is expected with
earlier Puppet 3 versions
> Set puppet min version_requirement to 3.8.7 + deps

- manifests/host.pp
- manifests/init.pp
- manifests/pool.pp
- manifests/pool6.pp
- metadata.json
- spec/classes/dhcp_spec.rb
- spec/defines/pool6_spec.rb
the goal is to get rid of validate_* functions. Bumping stdlib is
required to get the new datatypes.
> migrate to puppet4 datatypes

- README.md
- manifests/init.pp
Notify service only if manage_service is set to true
Signed-off-by: Anton Baranov <abaranov@linuxfoundation.org>
> Add flag to manage dhcp service

- spec/defines/ignoredsubnet_spec.rb
- templates/dhcpd.ignoredsubnet.erb
It looks like the syntax is incorrect on modern Puppet versions. This
changes it to the modern style and adds a test for it.
> Fix dhcp::ignoredsubnet template

- manifests/host.pp
- templates/dhcpd.host.erb
added parameter for ddns-hostname to allow for multiple static dhcp assignments per ddns hostname. this is necessary for hosts with two interfaces (wifi, ethernet)
> parameterised ddns-hostnames

- templates/dhcpd.conf-extra.erb
To use an option space added in extra_config in dhcpd.pools it needs to
be declared before it can be used.
> dhcpd.conf-extra: move includes below extra_config

- manifests/init.pp
This fixes an error when `manage_service` is false.
Fixes #170.
> Fix notification target

- spec/classes/dhcp_spec.rb
- spec/defines/dhcp_class_spec.rb
- spec/defines/host_spec.rb
- spec/defines/ignoredsubnet_spec.rb
eq() is very useless on array comparison when you want to debug:
```
expected: ["ddns-updates on;", "ddns-update-style standard;", "update-static-leases on;", "update-optimization ...1.1.1.in-addr.arpa. {", "  primary 1.1.1.1;", "  primary6 1:5ee:bad::c0de;", "  key rndc.key;", "}"]
got: ["ddns-updates on;", "ddns-update-style standard;", "update-static-leases on;", "update-optimization ...1.1.1.in-addr.arpa. {", "  primary 1.1.1.1;", "  primary6 1:5ee:bad::c0de;", "  key rndc.key;", "}"]
```
match_array will show which elements are missing and extra.
> Use match_array for better failure output

- manifests/init.pp
- metadata.json
The stdlib fix is part of 4.16.0
> Use IPv6 type validation for $nameservers_ipv6

- spec/classes/dhcp_spec.rb
- templates/debian/default_isc-dhcp-server
Since stretch, the /etc/defaults/isc-dhcp-server entry for the
interfaces to listen on has changed to INTERFACESv4. This change
reflects that.
Fixes #177 and closes #185
> Debian default ipv4 interfaces config has changed

- README.md
- manifests/init.pp
Setting Nameservers in Main Section per Default is not optimal,
In especially in cases where they are set in Pool.
This Request makes Default Nameserver Setting to an optional Setting.
> make main section nameservers optional

- manifests/host.pp
- spec/type_aliases/mac_spec.rb
- types/mac.pp
issue:
validation occurs of IP address in host resource but not mac address. a malformed mac address can break isc dhcp service.
added validation using stdlib::MAC type
n/a
> add mac address validation

- templates/dhcpd.conf-extra.erb
somebody missed a - in the erb template. This results in a bloated
config file with many empty lines.
> Don't add a newline between each DHCP option

- templates/dhcpd.conf-extra.erb
There are two whitespaces after each dhcp option. This is very confusing
and, depending on your editor config, this results in some warnings
(detected trailing whitespace...).
> Purge useless trailing whitespace in template

- README.md
- manifests/init.pp
If the `Package[$packagename]` resource is defined in another module,
it breaks with the use of this module. This allows the user to disable
the Package resource in this module.
na
> Add parameter to make installing the package optional

- README.md
- manifests/host.pp
- spec/defines/host_spec.rb
- templates/dhcpd.host.erb
This can be used where there's a need to have individual hosts vary from
those set for the subnet or globally.
Signed-off-by: John Florian <jflorian@doubledog.org>
I have use cases where I want certain hosts to have shorter DHCP lease times than those I prefer for global defaults.  The ISC DHCP daemon allows overriding the `max-lease-time` and `default-lease-time` parameters within a host record, now this module can too.  Both of these settings are entirely optional.  If you don't define them, the global (i.e., `dhcpd` class) defaults are used as before and there's no difference in the `dhcpd.hosts` file.
Ideally, this would be extended to `dhcp::pool` as well, because IIRC that too is possible, but I don't have that need.
none created
> allow dhcp::host to override default- and max-lease-time

- README.md
- manifests/host.pp
- spec/defines/host_spec.rb
- templates/dhcpd.host.erb
This adds 3 new optional parameters to `dhcp::host`:
* `on_commit`
* `on_release`
* `on_expiry`
Each of these accepts an array of strings representing statements that dhcpd is to perform when that event occurs for that host.
Signed-off-by: John Florian <jflorian@doubledog.org>
none have been created
> allow dhcp::host to set "on EVENT" handlers

- manifests/host.pp
- templates/dhcpd.host.erb
I often use dhcp to allocate hostnames or to distribute other options (eg routers) where I don't care about the IP address. I tried similar code to the above, but (using hiera) I received a message when I did not include an IP address:
`Evaluation Error: Error while evaluating a Resource Statement, Dhcp::Host[LGwebOSTV]: expects a value for parameter 'ip' (file: /etc/puppetlabs/code/environments/production/modules/dhcp/manifests/init.pp, line: 289)`
I have worked around this by setting the IP address to 0.0.0.0 and then ignoring it in the template but this seems like a kludge! 
Fixes #106
> Allow host declaration without IP.

- manifests/init.pp
Allow the `parameter` to take FQDN as well as IP address.
Fixes #239
> pxeserver (next-server) can be FQDN or IP address

- manifests/init.pp
- manifests/pool.pp
- manifests/pool6.pp
- spec/classes/dhcp_spec.rb
- spec/defines/pool6_spec.rb
- spec/defines/pool_spec.rb
- templates/dhcpd.conf-header.erb
- templates/dhcpd.pool.erb
- templates/dhcpd.pool6.erb
The event handlers are currently only supported for dhcp::host (see #216). These handlers can also exist globally in dhcpd.conf or in the pool definition dhcpd::pool and dhcpd::pool6. This PR extends support to these cases
Fixes #251
> Extend support for event clauses to global, pool and pool6

- manifests/init.pp
- manifests/pool.pp
- manifests/pool6.pp
- manifests/sharednetwork.pp
- spec/acceptance/class_spec.rb
- spec/defines/sharednetwork_spec.rb
- templates/dhcpd.sharednetwork.erb
Enable the grouping of dhcp-pools into shared-networks
Fixes #158
> Add support for grouping of dhcp-pools into shared-networks

- manifests/pool6.pp
- spec/acceptance/class_spec.rb
- spec/classes/dhcp_spec.rb
- spec/defines/pool6_spec.rb
Allow the same resource-title for pool and pool6-definitions
Currently you cannot give a dhcp and dhcp6-pool the same resource-title,
since the name would be shared by the concat::fragment. This is quite
unexpected, so make sure that we use a different title on the fragments
for pool6-defines.
> rename fragments for dhcp6-pools

- manifests/pool6.pp
fixes an issue resulting when PR #261 and #263 were both merged
make sure that pool6-definitions with shared-networks use the correct dependency now that PR #263 was merged too.
> Bugfix: use correct title in shared-network dependency

- manifests/pool.pp
- spec/defines/pool_spec.rb
- templates/dhcpd.pool.erb
This patch allows to specify a netmask to single hosts which differs from the global netmask of the pool.
It is useful in an edge case where a big pool is used with lots of ip-telephones where each telephone should be restricted to a `/32` (providing some special optionparameters).
It includes no break-changes, since it only introduces a `host_mask`-parameter which defaults to `mask`-parameter.
> allow to override host-subnetmask for pools

- manifests/init.pp
- manifests/params.pp
- metadata.json
- spec/classes/dhcp_spec.rb
- templates/redhat/sysconfig-dhcpd
Add support for CentOS Stream 9 and RHEL 9 by doing what the
CentOS 8 support patches should've done to not break on later releases yet again.
> Add CentOS Stream 9 and RHEL 9 support

- metadata.json
This pull request makes the module compatible to `puppetlabs/stdlib` 9.x. It also introduces compatibility to Debian 12 and Ubuntu 22.04.
> Support for puppetlabs/stdlib 9.x, concat 9.x, Debian 12, and Ubuntu 22.04
